version: '3.8'
services:
  postgres:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./quranapp_backend:/app/quranapp_backend
    ports:
      - "8000:8000"

volumes:
  postgres_data: