---
title: Quarapp Models
---
classDiagram
class Riwayah {
    <<enumeration>>
    Hafs
    Qaloon
}
class MushafPublisher {
    <<enumeration>>
    Madina
}
class User {
    String: id
    String: alias
    String: name
    String: surname
}
class Mushaf {
    Uuid: id
    MushafPublisher: publisher
    Riwayah: riwayah
}
class Surah {
    Int: number
    String: title
    String: description
    String: translate
}

class MushafPage {
    Uuid: id
    Int: index
    Uuid: mushafId
    String: lightModeLink
    String: darkModeLink
}
class Ayah {
    Uuid: id
    Uuid: mushafId
    Int: surahNumber
    Int: ayahInSurahNumber
}
class AyahPart {
    Uuid: id
    Uuid: ayahId
    Uuid: mushafPageId
    Int: partNumber = 0
    String: text
}
class SurahInMushaf {
    Uuid: firstPageInMushafId
    Int: surahNumber
}
class Recording {
    Uuid: id
    String: userId
    AyahPart: start
    AyahPart: end 
    String: audioUrl
    Date: createdAt
}
class SharedRecording {
    Uuid: recipientId
    Uuid: recordingId
    Date: createdAt
}
class AyahMarkers {
    Uuid: ayahPartId
    Int: orderId
    Int: x
    Int: y1
    Int: y2
    Bool: isNewLine
}
Recording *-- AyahPart: consist of
User -- Recording: creates
AyahPart --> Ayah
AyahPart --> MushafPage
Ayah --> Mushaf
Mushaf --> Riwayah
Mushaf --> MushafPublisher
SharedRecording --> Recording
AyahMarkers --> AyahPart
MushafPage --> Mushaf
SurahInMushaf --> MushafPage
SurahInMushaf --> Surah