---
title: Quaranize Models
---
classDiagram
class Riwayah {
    <<enumeration>>
    Hafs
    Qaloon
}
class MushafPublisher {
    <<enumeration>>
    Madina
}
class AyahPart {
    Uuid: id
    Uuid: mushafId
    Uuid: ayahId
    Int: partNumber = 0
    String: text
    Int: page
}
class Ayah {
    Uuid: id
    Riwayah: riwayah
    Int: surahNumber
    Int: ayahInSurahNumber
}
class Mushaf {
    Uuid: id
    MushafPublisher: publisher
    Riwayah: riwayah
}
class User {
    String: id
    String: alias
    String: name
    String: surname
}
class Recording {
    Uuid: id
    String: userId
    AyahPart: start
    AyahPart: end 
    String: audioUrl
    Date: createdAt
}
class SharedRecording {
    Uuid: recipientId
    Uuid: recordingId
    Date: createdAt
}
class AyahMarkers {
    Uuid: ayahPartId
    Int: orderId
    Int: x
    Int: y1
    Int: y2
    Bool: isNewLine
}
Recording *-- AyahPart: consist of
User -- Recording: creates
AyahPart --> Ayah
AyahPart --> Mushaf
Ayah --> Riwayah
Mushaf --> Riwayah
Mushaf --> MushafPublisher
SharedRecording --> Recording
AyahMarkers --> AyahPart