"""Updated models to v2 version -  added mushafs, mushafs pages and ayah parts markers tables

Revision ID: 144a5671307f
Revises: 853b37ec3555
Create Date: 2024-01-24 17:21:19.811942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Session

from src.dal.utils import fill_mushaf_for_existing_ayahs

# revision identifiers, used by Alembic.
revision: str = '144a5671307f'
down_revision: Union[str, None] = '853b37ec3555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mushafs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publisher', sa.Enum('MADINA', name='publisherenum'), nullable=False),
    # sa.Column('riwayah', sa.Enum('HAFS', 'QALOON', name='riwayahenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mushaf_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index', sa.SmallInteger(), nullable=False),
    sa.Column('mushaf_id', sa.UUID(), nullable=False),
    sa.Column('light_mode_link', sa.String(), nullable=True),
    sa.Column('dark_mode_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mushaf_id'], ['mushafs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ayah_part_markers',
    sa.Column('ayah_part_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('x', sa.SmallInteger(), nullable=False),
    sa.Column('y1', sa.SmallInteger(), nullable=False),
    sa.Column('y2', sa.SmallInteger(), nullable=False),
    sa.Column('is_new_line', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ayah_part_id'], ['ayah_parts.id'], ),
    sa.PrimaryKeyConstraint('ayah_part_id', 'order')
    )
    op.add_column('ayah_parts', sa.Column('mushaf_page_id', sa.UUID(), nullable=True))
    op.add_column('ayah_parts', sa.Column('ayah_part_text_id', sa.UUID(), nullable=True))
    op.create_foreign_key("ayah_parts_to_mushaf_pages_fk", 'ayah_parts', 'mushaf_pages', ['mushaf_page_id'], ['id'])
    op.create_foreign_key("ayah_parts_to_text_fk", 'ayah_parts', 'ayah_part_texts', ['ayah_part_text_id'], ['id'])
    # op.add_column('ayahs', sa.Column('mushaf_id', sa.UUID(), nullable=False))
    # op.create_foreign_key(None, 'ayahs', 'mushafs', ['mushaf_id'], ['id'])
    op.drop_column('ayahs', 'riwayah')
    op.alter_column('ayahs', 'surah_number', existing_type=sa.SMALLINT(), type_=sa.Integer(), existing_nullable=False)
    op.create_foreign_key("ayahs_to_surahs_fk", 'ayahs', 'surahs', ['surah_number'], ['id'])
    # ### end Alembic commands ###

    sa_enum = sa.Enum('HAFS', 'QALOON', name='riwayahenum')
    sa_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("mushafs", sa.Column("riwayah", postgresql.ENUM('HAFS', 'QALOON', name='riwayahenum'), nullable=False))

    #todo после того, как переведем БД на модель v2 на heroku инстансе, можно заменить кусок ниже просто на:
    # op.add_column('ayahs', sa.Column('mushaf_id', sa.UUID(), nullable=False))
    #=====
    op.add_column('ayahs', sa.Column('mushaf_id', sa.UUID(), nullable=True))
    with Session(op.get_bind()) as session:
        fill_mushaf_for_existing_ayahs(session)
    op.alter_column('ayahs', 'mushaf_id', nullable=False)
    #=====

    op.create_foreign_key("ayahs_to_mushafs_fk", 'ayahs', 'mushafs', ['mushaf_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('ayahs', sa.Column('riwayah', postgresql.ENUM('HAFS', 'QALOON', name='riwayahenum'), autoincrement=False, nullable=False))
    op.drop_constraint("ayahs_to_mushafs_fk", 'ayahs', type_='foreignkey')
    op.drop_column('ayahs', 'mushaf_id')
    op.drop_constraint("ayah_parts_to_text_fk", 'ayah_parts', type_='foreignkey')
    op.drop_constraint("ayah_parts_to_mushaf_pages_fk", 'ayah_parts', type_='foreignkey')
    op.drop_column('ayah_parts', 'ayah_part_text_id')
    op.drop_column('ayah_parts', 'mushaf_page_id')
    op.drop_constraint("ayahs_to_surahs_fk", 'ayahs', type_='foreignkey')
    op.alter_column('ayahs', 'surah_number', existing_type=sa.Integer(), type_=sa.SMALLINT(), existing_nullable=False)
    op.drop_table('ayah_part_markers')
    op.drop_table('mushaf_pages')
    op.drop_table('mushafs')
    # ### end Alembic commands ###

    op.execute("""DROP TYPE publisherenum""")
    op.add_column('ayahs', sa.Column('riwayah', postgresql.ENUM('HAFS', 'QALOON', name='riwayahenum'), autoincrement=False, nullable=True))
    op.execute("UPDATE ayahs SET riwayah = 'QALOON'")
    op.alter_column('ayahs', 'riwayah', nullable=False)

