"""Added id field for ayah part markers table

Revision ID: 15fb01b1f4e1
Revises: b4ce0692f9f3
Create Date: 2024-03-06 17:09:12.865469

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from src.dal.models import AyahPartMarker

# revision identifiers, used by Alembic.
revision: str = '15fb01b1f4e1'
down_revision: Union[str, None] = 'b4ce0692f9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ayah_part_markers', sa.Column('id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###
    with Session(op.get_bind()) as session:
        existing_markers_pks: list[tuple[uuid.UUID | int]] = session.query(
            AyahPartMarker.ayah_part_id, AyahPartMarker.order
        ).all()

    for (ayah_part_id, order) in existing_markers_pks:
        op.execute(
            f"UPDATE ayah_part_markers SET id = uuid('{uuid.uuid4()}') "
            f"WHERE ayah_part_id = uuid('{ayah_part_id}') AND ayah_part_markers.order = {order}"
        )

    op.alter_column('ayah_part_markers', 'id', nullable=False)
    op.drop_constraint(constraint_name="ayah_part_markers_pkey", type_="primary", table_name='ayah_part_markers')
    op.create_primary_key(constraint_name="ayah_part_markers_pkey", table_name='ayah_part_markers', columns=['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ayah_part_markers', 'id')
    # ### end Alembic commands ###
    # Primary key constraint for 'id' column is dropped automatically
    op.create_primary_key(
        constraint_name="ayah_part_markers_pkey", table_name='ayah_part_markers', columns=['ayah_part_id', 'order']
    )
