"""Added ayahs table and extended ayah parts table

Revision ID: 1a2778c519c9
Revises: 0181db885bcd
Create Date: 2023-10-24 20:27:30.808723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2778c519c9'
down_revision: Union[str, None] = '0181db885bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayahs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('surah_number', sa.SmallInteger(), nullable=False),
    sa.Column('ayah_in_surah_number', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ayah_parts', sa.Column('part_number', sa.SmallInteger(), nullable=True))
    op.execute("UPDATE ayah_parts SET part_number = -1")
    op.alter_column('ayah_parts', 'part_number', nullable=False)
    op.add_column('ayah_parts', sa.Column('ayah_id', sa.UUID(), nullable=True))
    op.execute("UPDATE ayah_parts SET ayah_id = '00000000-0000-0000-0000-000000000000'")
    op.alter_column('ayah_parts', 'ayah_id', nullable=False)
    op.create_foreign_key('ayah_parts_to_ayahs_fk', 'ayah_parts', 'ayahs', ['ayah_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ayah_parts_to_ayahs_fk', 'ayah_parts', type_='foreignkey')
    op.drop_column('ayah_parts', 'ayah_id')
    op.drop_column('ayah_parts', 'part_number')
    op.drop_table('ayahs')
    # ### end Alembic commands ###
