"""added reciter

Revision ID: 25779d22b738
Revises: 5e4726eae600
Create Date: 2024-01-22 22:57:10.077103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25779d22b738'
down_revision: Union[str, None] = '5e4726eae600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reciters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    # sa.Column('riwayah', sa.Enum('HAFS', 'QALOON', name='riwayahenum'), nullable=False), - tries to recreate enum
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    sa_enum = sa.Enum('HAFS', 'QALOON', name='riwayahenum')
    sa_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("reciters", sa.Column("riwayah", sa_enum, nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reciters')
    # ### end Alembic commands ###
