"""Changed publisher enum

Revision ID: 4136d4a1cc19
Revises: 4f8f162de84b
Create Date: 2024-03-08 17:57:49.017148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4136d4a1cc19'
down_revision: Union[str, None] = '4f8f162de84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Solution is taken from here: https://makimo.com/blog/upgrading-postgresqls-enum-type-with-sqlalchemy-using-alembic-migration/
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE publisherenum ADD VALUE 'JAWAMEE'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute("ALTER TYPE publisherenum RENAME TO publisherenum_old")
    op.execute("CREATE TYPE publisherenum AS ENUM('MADINA')")
    op.execute((
        "ALTER TABLE mushafs ALTER COLUMN publisher TYPE publisherenum USING "
        "publisher::text::publisherenum"
    ))
    op.execute("DROP TYPE publisherenum_old")
