"""added jwt tokens table

Revision ID: 4b7d13513916
Revises: 11c160d1b7ec
Create Date: 2024-01-15 20:04:10.464229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b7d13513916'
down_revision: Union[str, None] = '11c160d1b7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'refresh_token_expires')
    op.drop_column('tokens', 'access_token_expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('access_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tokens', sa.Column('refresh_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
