"""added surah

Revision ID: 5e4726eae600
Revises: 8b106a92ec04
Create Date: 2024-01-22 22:23:41.099564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from quran_data.data_files.surahs import surahs


# revision identifiers, used by Alembic.
revision: str = '5e4726eae600'
down_revision: Union[str, None] = '8b106a92ec04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('surahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('revelation_type', sa.String(), nullable=False),
    sa.Column('title_eng', sa.String(), nullable=False),
    sa.Column('title_eng_translation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
    op.bulk_insert(table, surahs)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surahs')
    # ### end Alembic commands ###
