"""added shared recordings

Revision ID: 815e860709a4
Revises: c90fa83110f4
Create Date: 2023-12-29 22:49:40.648310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815e860709a4'
down_revision: Union[str, None] = 'c90fa83110f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_recordings',
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('recipient_id', 'recording_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_recordings')
    # ### end Alembic commands ###
