"""Added ayahs table and extended ayah parts table

Revision ID: 932df5d3cae1
Revises: ec798855e3dc
Create Date: 2023-11-04 14:20:50.823251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90fa83110f4'
down_revision: Union[str, None] = 'ec798855e3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayahs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('surah_number', sa.SmallInteger(), nullable=False),
    sa.Column('ayah_in_surah_number', sa.SmallInteger(), nullable=False),
    sa.Column('riwayah', sa.Enum('HAFS', 'QALOON', name='riwayahenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ayah_parts', sa.Column('part_number', sa.SmallInteger(), nullable=True))
    op.execute("UPDATE ayah_parts SET part_number = -1")
    op.alter_column('ayah_parts', 'part_number', nullable=False)
    op.add_column('ayah_parts', sa.Column('ayah_id', sa.UUID(), nullable=True))
    op.execute("UPDATE ayah_parts SET ayah_id = '00000000-0000-0000-0000-000000000000'")
    op.alter_column('ayah_parts', 'ayah_id', nullable=False)
    op.create_foreign_key("ayah_parts_to_ayahs_fk", 'ayah_parts', 'ayahs', ['ayah_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ayah_parts_to_ayahs_fk", 'ayah_parts', type_='foreignkey')
    op.drop_column('ayah_parts', 'ayah_id')
    op.drop_column('ayah_parts', 'part_number')
    op.drop_table('ayahs')
    op.execute("""DROP TYPE riwayahenum""")
    # ### end Alembic commands ###
