"""create surah in mushaf

Revision ID: b4ce0692f9f3
Revises: 4f8f162de84b
Create Date: 2024-02-29 20:57:29.363446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ce0692f9f3'
down_revision: Union[str, None] = '4f8f162de84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surah_in_mushaf',
    sa.Column('first_page_id', sa.UUID(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_page_id'], ['mushaf_pages.id'], ),
    sa.ForeignKeyConstraint(['surah_number'], ['surahs.id'], ),
    sa.PrimaryKeyConstraint('first_page_id', 'surah_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surah_in_mushaf')
    # ### end Alembic commands ###
