"""update recording mistakes constraints

Revision ID: b747b1a516a7
Revises: d736791c85f4
Create Date: 2024-05-18 16:28:30.117385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b747b1a516a7'
down_revision: Union[str, None] = 'd736791c85f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recording_mistakes', ['commentator_id', 'recording_id', 'start_marker_id', 'end_marker_id', 'mistake_type'])
    op.alter_column('shared_recordings', 'is_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shared_recordings', 'is_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'recording_mistakes', type_='unique')
    # ### end Alembic commands ###
