"""added recording mistakes

Revision ID: d736791c85f4
Revises: e2bb3e5d3b85
Create Date: 2024-05-16 12:35:50.915351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd736791c85f4'
down_revision: Union[str, None] = 'e2bb3e5d3b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_mistakes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commentator_id', sa.String(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('start_marker_id', sa.UUID(), nullable=False),
    sa.Column('end_marker_id', sa.UUID(), nullable=False),
    sa.Column('mistake_type', sa.Enum('WORDING', 'LETTERS', 'TASHKEEL', 'TAJWEED', name='mistaketype'), nullable=False),
    sa.ForeignKeyConstraint(['commentator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['end_marker_id'], ['ayah_part_markers.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['start_marker_id'], ['ayah_part_markers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recording_mistakes_commentator_id', 'recording_mistakes', ['commentator_id'], unique=False)
    op.create_index('ix_recording_mistakes_recording_id', 'recording_mistakes', ['recording_id'], unique=False)
    op.add_column('shared_recordings', sa.Column('is_reviewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_recordings', 'is_reviewed')
    op.drop_index('ix_recording_mistakes_recording_id', table_name='recording_mistakes')
    op.drop_index('ix_recording_mistakes_commentator_id', table_name='recording_mistakes')
    op.drop_table('recording_mistakes')
    # ### end Alembic commands ###
