name: Pull Request Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  POSTGRES_USER: ${{secrets.POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
  DB_HOST: ${{secrets.DB_HOST}}
  POSTGRES_DB: ${{secrets.POSTGRES_DB}}

defaults:
  run:
    working-directory: ./quranapp_backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Dependencies install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Tests
        run: |
          pytest
        