name: Heroku Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: ./quranapp_backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Dependencies install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Tests
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER_PROD}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD_PROD}}
          DB_HOST: ${{secrets.DB_HOST_PROD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB_PROD}}
        run: |
          pytest
        